version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: exerciseModule4
    volumes:
      - ./data:/var/lib/postgresql/data